### ISSUE TITLE
Claim of property of the provided files

### ISSUE THREAD

**Issue by dreamwhite** [brosahay/Dell-Inspiron-5370-DSDT-Patch#4]
Hi there, a few days ago I decided to temporarely shutdown from public my original repository called dreamwhite/dell-inspiron-5370-hackintosh available on github
Also a few days ago I noticed that a GitHub account which had the username 193XXXXXXXX (or something along these lines) forked my repository.
I analyzed your repository and found that YOU stole those files from MY repository. How do I know that?

PR LINK: [link](https://github.com/brosahay/Dell-Inspiron-5370-DSDT-Patch/pull/3/commits/1dad32f2b4574fbde425f6ec43975269912acc94)

The naming of the removed files, especially

ACPI/SSDT-2-xh_OEMBD.aml
ACPI/SSDT-GPI0.aml
ACPI/SSDT-GPRW.aml
ACPI/SSDT-MCHC-SBUS.aml

And other tools are stolen from my work. There's no mention of my work there.

How do I know this? Since GIT has track of everything let's disassemble ACPI/SSDT-2-xh_OEMBD.aml and check the content...

Oh wow, there's a weird method called GENG. Uhm lemme think, maybe that I got it from @Gengik84 work? But hey, it's just a name let's move on.
Oh wait, the external references list has just a bunch of ports, without explaining why only just a bunch of ports are named. Lemme think, probably I did because I didn't wanted to include unused ports?
But hey, again there's clearly no mention of @Gengik84 work, neither mine.

Honestly this kind of people like you is probably the worst type you could ever imagine. No fucking mention of other people work. This is called stealing other's people code.
The config.plist structure is stolen from my work. How do I know? Let's check the iGPU patch and read the alldata stuff. Oh wait, before I forget about it, check the MMIO Whitelist stuff. Can you explain why you added 4278190080 region? Is there any kind of documentation we can consult?

Kindly,
dreamwhite

**Comment by brosahay** [comment]
Hey @dreamwhite happy to provide the references. I had looked into a lot of github code or EFI folders from other forums/reddit to check if it worked, so I have really forgotten where I gathered the files from. I am not a person not to give credit where it is due. I am not debating you on the efforts you have put in. Thanks for reaching out, can you let me know if you want to take these files down or I will happily add credit where its due.

Regards,
brosahay

**Comment by dreamwhite** [comment]
> Hey @dreamwhite happy to provide the references. I had looked into a lot of github code or EFI folders from other forums/reddit to check if it worked, so I have really forgotten where I gathered the files from. I am not a person not to give credit where it is due. I am not debating you on the efforts you have put in. Thanks for reaching out, can you let me know if you want to take these files down or I will happily add credit where its due.
> 
> Regards,
> brosahay

Good morning, thank you so much for replying :)
Well, at the moment I'm restoring my GitHub repo (dreamwhite/dell-inspiron-5370-hackintosh) which is at the moment a private repo. In the following days I'll try to complete this process and eventually ping you.

Kindly,
dreamwhite

**Comment by brosahay** [comment]
> > Hey @dreamwhite happy to provide the references. I had looked into a lot of github code or EFI folders from other forums/reddit to check if it worked, so I have really forgotten where I gathered the files from. I am not a person not to give credit where it is due. I am not debating you on the efforts you have put in. Thanks for reaching out, can you let me know if you want to take these files down or I will happily add credit where its due.
> > Regards,
> > brosahay
> 
> Good morning, thank you so much for replying :)
> Well, at the moment I'm restoring my GitHub repo (dreamwhite/dell-inspiron-5370-hackintosh) which is at the moment a private repo. In the following days I'll try to complete this process and eventually ping you.
> 
> Kindly,
> dreamwhite

Sure, do let me know. One small thing, it was kind of rude for you to presume my nature based on this or the fact that I would not know how to patch DSDT/ identify patches that might work. I didn't do a lot of work on the laptop until recently when the DW1860 wifi card started working on the laptop suddenly. Until then I had just used this laptop once to boot and install hackintosh. I used to use another hardware as my primary hackintosh. In any case let me know when you have your repository ready and what to do with the files you created ?

Regards,
brosahay
